import time
from dir.func import slow_text

slow_text('Loading...')
time.sleep(1)
time.sleep(0.5)
print()
slow_text('25%...')
time.sleep(0.4)
print()
slow_text('50%...')
time.sleep(0.3)
print()
slow_text('75%...')
time.sleep(0.2)
print()
slow_text('100%...')
print()
time.sleep(0.1)
print()
slow_text('Welcome player to the Echoes of The Forgotten!')
print()

print()
input('Press ENTER to continue...')
print()
time.sleep(0.5)
slow_text('Enter your name: ')
name = input()
print()
time.sleep(1)
name = name.strip()
print(name, 'eh, a fine name for a warrior we need you!')
time.sleep(1)
print()

slow_text('Before we begin, choose your path!')
